trigger:
- main  # Adjust the branch name as necessary

pool:
  vmImage: 'ubuntu-latest'  # You can change the VM image if needed

variables:
  azureSubscription: 'Azure subscription 1'  # Name of the Azure subscription
  appName: 'chinonso-bincom-api'  # Name of the Azure Web App
  resourceGroup: 'bincom_rg'  # Resource group containing the Web App
  packagePath: '$(System.DefaultWorkingDirectory)/**/*.zip'  # Path to your package

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2  # Change if you're using a different technology
      displayName: 'Build the application'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/ContactSession1'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        include: '**/*'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
        resourceGroupName: $(resourceGroup)
